steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=eu.gcr.io/$PROJECT_ID/postgresql-client', '.']
- name: 'eu.gcr.io/$PROJECT_ID/postgresql-client'
  args: ['--version']
images: ['eu.gcr.io/$PROJECT_ID/postgresql-client']